apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: web
    type: multi
spec:
  containers:
  - name: main-app
    image: nginx:1.25.3
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
    ports:
    - containerPort: 80

  - name: log-viewer
    image: busybox:1.36
    command: ['sh', '-c', 'tail -f /var/log/nginx/access.log']
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx

  volumes:
  - name: logs
    emptyDir: {}
