version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudmart-postgres
    environment:
      POSTGRES_DB: cloudmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: cloudmart-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    container_name: cloudmart-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/cloudmart
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
